feat: add asset edit functionality
deltaDAO/nautilus pull request #58
Opened 2023-09-20 22:34 UTC by Abrom8

closes #10 

## Proposed Changes
- Edit asset functionality

2023-11-06 08:49 UTC, moritzkirstein requested changes

2023-11-06 08:49 UTC, moritzkirstein commented on src/Nautilus/Asset/Service/ServiceBuilder.ts
> +    if (algorithms.length === 0) {
issue: could be undefined
```suggestion
    if (algorithms?.length === 0) {
```

2023-11-06 08:49 UTC, moritzkirstein commented on src/utils/helpers/trusted-algorithms.ts
> +  nautilus: Nautilus
suggestion: as this is a utility function, I prefer for it to work without relying on any repo class instances. In this case I think `nautilus` is only used to retrieve the `metadataCacheUri` from the config. To break responsibilities a bit better here, imo the helper should simply work with passing a `metadataCacheUri` parameter.

```ts
export async function getPublisherTrustedAlgorithms(
  dids: string[],
  metadataCacheUri: string
) {
  const assetPromises = dids.map((did) =>
    getAsset(metadataCacheUri, did)
  )
// ... 
}
```

2023-11-06 08:49 UTC, moritzkirstein commented on src/utils/helpers/trusted-algorithms.ts
> +    const containerChecksum =
suggestion: a comment linking to the definition/spec would be useful here

2023-11-10 15:05 UTC, moritzkirstein commented on src/Nautilus/Nautilus.ts
> +        }
comment: add a TODO to check if related problems can be solved on caching layer or not

2023-11-10 15:07 UTC, moritzkirstein commented on src/index.ts
> +export { getPublisherTrustedAlgorithms } from './utils/helpers/trusted-algorithms'
reminder: can be removed
optionally: export * from utils can be added

2023-11-20 10:09 UTC, Abrom8 commented on src/Nautilus/Asset/NautilusDDO.ts
> +      }
Created #61 for that.

2023-11-23 13:44 UTC, moritzkirstein commented on src/utils/aquarius.ts
> +): Promise<{ [key: string]: Asset }> {
nitpick: we could rename `key` to `did` to indicate to the user how these are used

2023-11-23 13:44 UTC, moritzkirstein commented on src/utils/helpers/trusted-algorithms.ts
> +    if (service.addedPublisherTrustedAlgorithms.length > 0) {
suggestion: it makes sense utilizing the early return / continue pattern here

2023-11-24 10:30 UTC, moritzkirstein approved these changes

2023-11-24 10:30 UTC, moritzkirstein commented on src/utils/constants.ts
> +export const AQUARIUS_ASSET_EXTENDED_DDO_PROPS: AssetSpecificProps[] = [
comment: let's add a TODO to look into type optimization at some point. Not a high prio for this PR imo

2023-11-24 14:55 UTC, merged